In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
sentences = [
    'I love machine learning',
    'Machine learning is amazing',
    'I enjoy deep learning',
    'I like playing cricket',
    'Cricket is a great sport'
]

In [3]:
# text --> vectors
vectorizer = TfidfVectorizer()

In [4]:
vectors = vectorizer.fit_transform(sentences)

In [5]:
vectors

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 17 stored elements and shape (5, 12)>

In [6]:
similarity_matrix = cosine_similarity(vectors)

In [7]:
similarity_matrix

array([[1.        , 0.45753378, 0.19782163, 0.        , 0.        ],
       [0.45753378, 1.        , 0.17283464, 0.        , 0.21600005],
       [0.19782163, 0.17283464, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.22001359],
       [0.        , 0.21600005, 0.        , 0.22001359, 1.        ]])

In [8]:
query  = ['I love deep learing']

In [9]:
query_vec = vectorizer.transform(query)

In [10]:
score = cosine_similarity(query_vec,vectors)

In [11]:
query[0]

'I love deep learing'

In [12]:
score

array([[0.4880163 , 0.        , 0.45189104, 0.        , 0.        ]])

In [13]:
score.argmax()

0

In [14]:
import numpy as np

In [15]:
movies = {
    'Avengers' :     [1,0,0,1],
    'Iron Man' :     [1,0,0,1],
    'The notebook' : [0,0,1,0],
    'Superbad' :     [0,1,0,0],
    'Titanic' :      [0,0,1,0]
}

In [18]:
movies_names = list(movies.keys())

In [20]:
movies_names

['Avengers', 'Iron Man', 'The notebook', 'Superbad', 'Titanic']

In [23]:
movie_vectors = np.array(list(movies.values()))

In [24]:
movie_vectors

array([[1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [25]:
similarity_matrix = cosine_similarity(movie_vectors)

In [26]:
similarity_matrix

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.]])

In [30]:
for i in range(len(movies_names)):
    for j in range(len(movies_names)):
        print(f'{movies_names[i]} vs {movies_names[j]} = {similarity_matrix[i][j]:.2f}')

Avengers vs Avengers = 1.00
Avengers vs Iron Man = 1.00
Avengers vs The notebook = 0.00
Avengers vs Superbad = 0.00
Avengers vs Titanic = 0.00
Iron Man vs Avengers = 1.00
Iron Man vs Iron Man = 1.00
Iron Man vs The notebook = 0.00
Iron Man vs Superbad = 0.00
Iron Man vs Titanic = 0.00
The notebook vs Avengers = 0.00
The notebook vs Iron Man = 0.00
The notebook vs The notebook = 1.00
The notebook vs Superbad = 0.00
The notebook vs Titanic = 1.00
Superbad vs Avengers = 0.00
Superbad vs Iron Man = 0.00
Superbad vs The notebook = 0.00
Superbad vs Superbad = 1.00
Superbad vs Titanic = 0.00
Titanic vs Avengers = 0.00
Titanic vs Iron Man = 0.00
Titanic vs The notebook = 1.00
Titanic vs Superbad = 0.00
Titanic vs Titanic = 1.00
