In [29]:
import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

In [30]:
from tensorflow.keras.layers import (
    Embedding,
    SimpleRNN,
    Dense
)

from sklearn.model_selection import train_test_split

In [31]:
texts = [
    "i love this movie",
    "this movie is amazing",
    "fantastic acting and story",
    "i hate this movie",
    "very bad experience",
    "worst film ever"
]

labels = [
    1,
    1,
    1,
    0,
    0,
    0
]

In [32]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(texts)

In [33]:
sequences = tokenizer.texts_to_sequences(texts)

In [34]:
sequences

[[3, 4, 1, 2],
 [1, 2, 5, 6],
 [7, 8, 9, 10],
 [3, 11, 1, 2],
 [12, 13, 14],
 [15, 16, 17]]

In [35]:
X = pad_sequences(sequences, maxlen=5)

In [36]:
X

array([[ 0,  3,  4,  1,  2],
       [ 0,  1,  2,  5,  6],
       [ 0,  7,  8,  9, 10],
       [ 0,  3, 11,  1,  2],
       [ 0,  0, 12, 13, 14],
       [ 0,  0, 15, 16, 17]], dtype=int32)

In [37]:
y = np.array(labels)

In [38]:
y

array([1, 1, 1, 0, 0, 0])

In [39]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.20, random_state=42)

In [40]:
# Deep rnn
model = Sequential()

model.add(Embedding(input_dim = 50, output_dim=16, input_length=5))

model.add(SimpleRNN(32,return_sequences=True)) #

model.add(SimpleRNN(32))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [41]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [42]:
model.fit(X_train,y_train, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.7500 - loss: 0.6708
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7500 - loss: 0.6338
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.5983
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.5641
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 1.0000 - loss: 0.5311
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.4991
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.4684
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.4390
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.4112
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7500 - loss: 0.3852
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7500 - loss: 0.3609
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.3382
Epo

In [88]:
text = ['fantastic acting and story']

In [89]:
seq = tokenizer.texts_to_sequences(text)

In [90]:
seq

[[7, 8, 9, 10]]

In [91]:
seq = pad_sequences(seq,maxlen=5)

In [92]:
pred = model.predict(seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


In [93]:
pred

array([[0.98909914]], dtype=float32)

In [94]:
pred >= 0.5

array([[ True]])