In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [2]:
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

In [3]:
y = np.array([4,5,6,7])

In [7]:
X = X.reshape(X.shape[0], X.shape[1], 1)

In [4]:
X.shape[0]

4

In [6]:
X[0]

array([1, 2, 3])

In [8]:
X    # (samples, timesteps, features)

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [ ]:
Sample(4) --- timesteps (3) --- feature(1)

In [26]:
model = Sequential()

In [27]:
model.add(SimpleRNN(10, activation='tanh', input_shape=(3,1)))  # 3 timesteps ---> 1 feature
model.add(Dense(1))

In [28]:
model.compile(
    optimizer='adam',
    loss='mse'
)

In [39]:
model.fit(X,y, epochs=4000, verbose=0)

In [40]:
test = np.array([[5,6,7]])

In [41]:
test = test.reshape(1,3,1)

In [42]:
test

array([[[5],
        [6],
        [7]]])

In [43]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[7.1705856]], dtype=float32)